defmodule TelemetrySpy do
  @moduledoc false
  def handle_event(name, measurements, metadata, _config) do
    IO.puts("\n[Telemetry] #{inspect(name)}")
    IO.puts("  Measurements: #{inspect(measurements)}")
    IO.puts("  Metadata:     #{inspect(metadata)}")
  end
end

ExUnit.start()

# # Enable this to see telemetry events generated by the tests
# #
# # Global Telemetry Spy: Prints all pool events to the console during tests.
# # Comment out this block to silence telemetry output.
# :telemetry.attach_many(
#   "global-telemetry-spy",
#   [
#     [:elastic_pool, :worker, :start],
#     [:elastic_pool, :worker, :stop],
#     [:elastic_pool, :worker, :unknown_message],
#     [:elastic_pool, :pool, :status]
#   ],
#   &TelemetrySpy.handle_event/4,
#   nil
# )
